### PR TITLE
Nightly

### PR DESCRIPTION
**Pull request by fkleuver**
This sets up a nightly build+publish. In summary, here's the workflow:

- Scheduled at 0:00 UTC, CircleCI runs the regular build+lint+test+bundle on the current master branch
- Then it `git add --force` the bundled outputs in the `dist` folder and merges them into the `dev` branch
- The act of pushing to `dev` by CircleCI then triggers the next workflow which bumps the version with a `-dev.yyyymmdd` tag and publishes to npm to `--tag dev`

Notes:
- The major.minor.patch version stays the same, only the nightly tag is added. So today's nightly would have published to `1.6.8-dev.20181219`
- No changelog is generated because there is not sufficient information to be extracted from the commit messages, so normal releases still need to be manually bumped and published.
- This is adapted from the workflow I implemented at Aurelia, but simplified due to being single package. It's therefore also not 100% tested. The first upcoming nightly might fail somehow.
- Any failure will abort the workflow so there is no risk of publishing garbage, just a risk of, well, not publishing at all.

@KFlash sound good to you? any questions/concerns?

### CODE REVIEW

**Comment by fkleuver** [comment]
Where do you see it failing?

**Comment by KFlash** [comment]
Can't you look at the bottom of the page? **Codacy/PR Quality Review**

**Comment by fkleuver** [comment]
> CircleCI is failing

That's what you said

> Codacy/PR Quality Review

It's nagging about style issues in build scripts..

**Comment by KFlash** [comment]
@fkleuver You merge this?

**Pull request merged**
