### PR TITLE
Revert "upgrade: devdeps"

### PR DESCRIPTION
**Pull request by KFlash**
Reverts cherow/cherow#182

@Aladdin-ADD ?

### CODE REVIEW

**Comment by Aladdin-ADD** [comment]
?

**Comment by KFlash** [comment]
Accidents happen my friend! Ignore it.  你能复习我的公关吗？

**Comment by Aladdin-ADD** [comment]
sure, I will, but plz give me some more time~

**Comment by Aladdin-ADD** [comment]
sure, all tests pased (also on CI). am I missing something?

**Pull request closed without merging**
