### PR TITLE
chore: upgrade some deps (fixes #240)

### LINKED ISSUE #240: Need to update package.json
Package.json need to be updated

Cc/ @fkleuver @Aladdin-ADD @g-plane

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
todo: confirm all the tests passed

### CODE REVIEW

**Comment by g-plane** [comment]
@KFlash What's wrong with that TypeScript error?

**Comment by Aladdin-ADD** [comment]
sure, I will try to fix it later.

**Comment by fkleuver** [comment]
@Aladdin-ADD Since this is a monorepo, next time please take into account the individual packages package.json as well. Now all dependencies are out of sync. I'm addressing this in https://github.com/cherow/cherow/pull/243

**Comment by Aladdin-ADD** [comment]
oops, sorry for not familiar with the mono repo. I thought the tests passed, and no error reported..

maybe we can add a para about it in `contributing.md`.

**Comment by fkleuver** [comment]
Actually it's probably fine for the current setup, I just noticed it during the workflow rework ( `npm ci` + `lerna bootstrap --ci --hoist` do not accept this and require everything to be in sync)

**Pull request merged**
