### PR TITLE
Re-export modules via cherow.ts & rename JSXElement

### PR DESCRIPTION
**Pull request by fkleuver**
For #86

### CODE REVIEW

**Comment by KFlash** [comment]
This looks ok for now. You are exporting some internals, but it's ok. One of the plans I had for the next version too (*modular*). So Merging and will push soon to NPM

**Comment by fkleuver** [comment]
Just an FYI, you could add `/*@internal*/` right above internal exports, and then the `"stripInternal": true` option in `tsconfig.json` will get rid of them in the declarations.

**Comment by KFlash** [comment]
Just updated the readme in the next branch so you can see my plans.  [Found here](https://github.com/cherow/cherow/blob/next/README.md#breaking).

So It's ok if internals are exposed for now.

**Comment by fkleuver** [comment]
Neat. Thanks :)

**Comment by KFlash** [comment]
@fkleuver Can you checkout the bleeding branch and see if this PR is still valid for the new code?

**Comment by fkleuver** [comment]
It doesn't seem like it, because some changes are in `src/flags.ts` and that file is gone now. That also makes the re-exports invalid. Though re-exporting all of the current files doesn't seem to give any conflicts.

**Comment by KFlash** [comment]
Ok. I will export everything before I push to NPM, or do you want to send a PR to the bleeding branch?
And if you want some changes to the core, other options etc, it's a good time to let me know now.

**Comment by fkleuver** [comment]
Can always do that after the fact. I'm a little busy at the moment.

However now that you mention it, considering my use case: I use Cherow in an Aurelia plugin to parse function bodies during runtime and extract various pieces of information (which are then used to apply conventions and auto-configure other components).

I actually had to copy the whole Cherow source over to my app (adding you to acknowledgements ofc) and change the access of parser methods (and I think I had to change a few other things) to be able to parse standalone functions. Works great by the way. Would be nice though if your plugin exposed the whole parser out-of-the-box so I don't have to resort to that kind of hackery :)

**Comment by KFlash** [comment]
@fkleuver To get back to this. The entire code is out in open now, so could you try to add same PR for bleeding when you are not busy?

And  let me know what you want to export, and what options you would need for the future. You want all main methods exported? I'm now finalizing this.

**Comment by fkleuver** [comment]
I've taken a first good look at it, and loving the new structure. Really amazing work you're doing!

So I started by trying a plain simple "export all", turns out there's a naming conflict between the `Parser` interface in `types.ts` and the `Parser` class in `parser/parser.ts`.

Two questions here:
1. Shouldn't the `Parser` class implement the `Parser` interface?
2. Should either the `Parser` interface be renamed to `IParser` (as is a typical convention for interfaces), or should instead the `Parser` class be renamed to `ParserImpl`?
(the latter since renaming one interface kind-of means the rest of them should be renamed too, and I assume you're not too fond of that idea)

**Comment by fkleuver** [comment]
Thought about the namespaces too, I think typescript mostly does it so they can more easily manage keeping certain parts of the API internal and not have to import everything everywhere.

Put `/*@internal*/` on the namespace to make everything internal, and a `/// reference` to the file gives you all of its exports. Could make the codebase a bit cleaner. To consumers it's no different, so no harm can be done at least.

Regarding interfaces, looking at [this thread](https://github.com/Microsoft/TypeScript-Handbook/issues/121) the opinions are very divided and discussion is inconclusive. I see [good points against the prefix](https://github.com/Microsoft/TypeScript-Handbook/issues/121#issuecomment-352171615) as well.

Ultimately it would depend on whether your users are mostly .NET folks or Java/JavaScript folks, and it's probably the latter. So maybe `Impl` suffix is the way to go. Or divide the interface up into smaller (differently named) parts and let the parser implement all of them.

Need to think about it.

So far everything else looks silky smooth!

**Comment by KFlash** [comment]
I think a NS is the correct direction for this, but I will let you think about this. For now I need to finish the last things on my TODO so I can push this to master.

**Comment by fkleuver** [comment]
Agreed on the namespaces, can't go wrong there.

It's the interfaces I'm not sure about.  It's also possible to do `export const Parser: Parser = { ... }`. Just have to port the class to a const, but then you're rid of the naming conflict without having to make any other changes. Not sure if there's any impact on performance though.

**Comment by KFlash** [comment]
If I do what you suggest I can't see any impact on performance.  I will push a change shortly.

**Pull request merged**
