### PR TITLE
chore(cherow): rm unused var

### PR DESCRIPTION
**Pull request by Aladdin-ADD**

### CODE REVIEW

**Comment by KFlash** [comment]
ai! That's errors returned from the shared lookup table for both templates and string.

**Comment by KFlash** [comment]
This pull request **fixes 5 alerts** when merging 7060f9733d358b5181b70eef369a894bc20b9f42 into b0ef67869477b6ef37901d84cc21df8ce544d508 - [view on LGTM.com](https://lgtm.com/projects/g/cherow/cherow/rev/pr-c7180cc5fc9b4fb97afb459f7e267cd1c5b12a3c)

**fixed alerts:**

* 5 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by g-plane** [comment]
@KFlash Should we let TypeScript or TSLint detect unused code and unreachable code?

**Comment by KFlash** [comment]
A good idea, and I'm fixing this "dead" code now.

**Pull request closed without merging**
