### PR TITLE
chore: add prettier & pre-commit (fixes #178)

### LINKED ISSUE #178: Use Prettier on partial files.
The code in this repository is really very messy and it's hard to read. The source code of cherow is worth learning, but I have trouble to read it because of the mess of the code.

I know there are some files which shouldn't be formatted by Prettier, such as https://github.com/cherow/cherow/blob/master/packages/cherow/src/common.ts . Thus, we can run Prettier on partial files, instead of all the source code.

**We can use `.prettierignore`.**

Additionally, we can use husky to add a git `precommit` hook to do the work automatically.

@KFlash @fkleuver What do you think of this?

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
Signed-off-by: weiran.zsd <weiran.zsd@alibaba-inc.com>

the pr enforces prettier coding style:
it add a pre-commit hook to check if the staged files are well-formatted. if no, it will give a hint like this:

image

so you have 3 choices:

1. `npm run prettier` to format the changed files.
2. `npm run prettier-all` to format all the files in the repo
3. `git commit -n` to skip the pre-commit hooks.

### CODE REVIEW

**Comment by Aladdin-ADD** [comment]
you can use `// prettier ignore` to avoid some code formatting, otherwise it will format your code on the background. 

and you may want an editor integration to do format-on-save.

refs:https://prettier.io/docs/en/editors.html

**Comment by fkleuver** [comment]
You know this will go horribly wrong right? @KFlash is going to forget about the // ignore and then complain about code being formatted horribly

**Comment by KFlash** [comment]
@fkleuver Using `// prettier ignore` isn't that hard if @Aladdin-ADD add the lines where they should be in the first place.

**Comment by fkleuver** [comment]
@KFlash there are many thing that aren't hard but you manage to make them so ;)
If you add a new file for example then @Aladdin-ADD won't be around to sneak in the `// prettier ignore`
In any case I just don't see the benefit. It would be much better if you just hand selected particular pieces of code and ran autoformat on them, and perhaps @Aladdin-ADD and others do the occasional PR with the same thing. Do it piecemeal. Not everything at once

**Comment by KFlash** [comment]
@Aladdin-ADD Is this ready to be merged? Kind of needed in my re-write.

**Comment by Aladdin-ADD** [comment]
not yet, I was considering adding a script to run prettier, rather than doing it on the background.

will finish it in the weekend.

**Comment by KFlash** [comment]
@fkleuver Well. It works okay, except I don't understand why it split up some code over several lines

```js
      declaration = parseLexicalDeclaration(
        state,
        context,
        BindingType.Const,
        BindingOrigin.Export,
        scope
      );
```

**Comment by futagoza** [comment]
@KFlash Maybe it's the [printWidth](https://prettier.io/docs/en/options.html#print-width) option, which is by default set to 80

**Comment by KFlash** [comment]
@futagoza Probably, but I let @Aladdin-ADD adjust this. It's his PR

**Comment by Aladdin-ADD** [comment]
@cherow/cherow-team 
I've updated the OP, and it's ready to be reviewed! 🚀

**Comment by KFlash** [comment]
@Aladdin-ADD Can you add an exception for "src/token.ts" and "src/unicode.ts" ?  No need to format this files, and the last file is auto-generated.

**Comment by KFlash** [comment]
@Aladdin-ADD Merge?

**Pull request merged**
