### PR TITLE
Generate tsd when build (fix #80)

### LINKED ISSUE #80: npm package doesn't contain tsd
**Code**

Import in typescript files.
```ts
import cherow from 'cherow'
```

**Expected behavior:**

Can get type hints

**Actual behavior:**

Can not.

### PR DESCRIPTION
**Pull request by zaaack**
@KFlash I changed the entry point to `lib/cherow.js` to get type hints, not sure it's OK.

### CODE REVIEW

**Comment by KFlash** [comment]
Changing the entry point shouldn't be an issue unless  someone get confused. Did you try to build it? I notived you changed somrthing in rollup conf. 

Im still on mobile, but will merge this soon and push to Npm soon as I'm back again behind a keyboard.

**Comment by KFlash** [comment]
@zaaack look at this message

```js
89Cannot glob `'./build/src/*.*'`: Cannot copy from `C:\projects\cherow\'.\build\src\*.*'` to `C:\projects\cherow\lib\*.*'`: cannot stat path `C:\projects\cherow\'.\build\src\*.*'`: ENOENT: no such file or directory, stat 'C:\projects\cherow\'.\build\src\*.*''
90npm ERR! code ELIFECYCLE
91npm ERR! errno 1
92npm ERR!
```

**Comment by zaaack** [comment]
Now I'm confused, I changed several `cp` package in nodejs, the error message became this:
```sh
./build/src/cherow.js → ./dist/cherow.js, ./dist/cherow.mjs...
78created ./dist/cherow.js, ./dist/cherow.mjs in 1.3s
79
80> cherow@1.2.7 build:lib C:\projects\cherow
81> tsc --skipLibCheck -t es2015 --m commonjs && rimraf lib && shx cp -R 'build/src' lib
82
83cp: no such file or directory: 'build/src'
84npm ERR! code ELIFECYCLE
85npm ERR! errno 1
86
```

I don't have access to a windows device for some time, cannot try it on windows.

**Comment by KFlash** [comment]
Appveyor passing now. Im merging this and fix it soon.

**Pull request merged**
