### PR TITLE
re-exports, add namespaces, fix a few linting errors

### PR DESCRIPTION
**Pull request by fkleuver**
Timing seems a bit unfortunate lol. Trying to merge the changes atm but just letting you know that this is incoming (if you agree with changes, that is)

### CODE REVIEW

**Comment by KFlash** [comment]
@fkleuver the `unicode.ts` file is not what it look like. It's actually generated, so here you would need to add the namespace code to the file in the `scripts folder` in root. If not this will be overwritten if you re-generate unicode.

**Comment by KFlash** [comment]
Ok. And try running `npm run prebuild` + `npm run build` when you think you are done just to make sure it's bundle correctly. And I guess the `lib folder` is not needed now, and same with `npm run build:lib`

**Comment by fkleuver** [comment]
I need to go for a bit. I believe it's only a small piece I'm still missing - vscode/tslint resolve the namespace in the tests, but the test runner apparently doesn't (cherow not defined). Will see if I can fix that in an hour give or take

**Comment by KFlash** [comment]
No rush. I'm occupied with some private stuff and not doing any development for awhile. Does it bundle?  Btw. Great work!

**Comment by fkleuver** [comment]
F** me, turns out the typescript and vscode teams are pulling a few tricks with custom scripts to make this work. I'm getting a build output that seems relatively ok at first glance (currently doing `amd` with single file output).

Tests won't run because const enums are getting filtered out even if I explicitly disable that in tsconfig and do a regular import from the build outputs. Getting second thoughts about whether or not this is a good approach. Was meant to simplify things, not make them a couple of notches harder lol.

**Comment by KFlash** [comment]
Ok. And also note that Rollup are used for bundling after Ts are done with them. This still works as before?

**Comment by fkleuver** [comment]
Appears to work yes. Though the minified version grew from 63kb to 94kb, seems to be from all the namespace assignments throughout the bundled output. Double checked typescript, they have this too. Might be better to go with a 1 or 2 letter abbreviation instead of `cherow` for the namespace.

I'm a bit stuck on the tests though (I'm only really familiar with Karma). Directly importing the typescript sources doesn't really work due to the namespaces, and referencing the transpiled output prevents the tests from compiling because the const enums are inlined (or at least not accessible). 

TypeScript has a very intricate custom build/test script to accomplish all this

What about we just conclude this to be a failed experiment ("now we know") and export some submodules as aliased instead? Achieves a similar effect and doesn't require all this hackery..

**Comment by KFlash** [comment]
Well. The  minified can't exceed 63 kb. One of the goal with this is to be as lightweight as possible. And for the rest, it's your decision as long as we in the end get this TS types fixed. 
But I may suggest that you look at the repo for the bundler used in this project. They seem to have solved a similar issue

**Comment by fkleuver** [comment]
The types were already sorted when you turned the Parser class into an object, the namespaces just seemed like they could make the "export everything" part a bit cleaner. Turns out it doesn't accomplish that, I misjudged the exterior of typescript and vscode projects. And if the bundle size can't exceed 63kb then namespaces are by definition a no-go as they *will* increase bundle size to some extent. 

I'm rolling back the namespaces changes for now, so at least there is a working thing with the exports. I'll need to learn more about rollup before I attempt another undertaking like this, because it's pointless if the bundle size increases that much.

**Comment by KFlash** [comment]
Ok. I will merge this as is, and eventually come back to this later when figured out the namespace.

**Comment by fkleuver** [comment]
hold on a sec

**Comment by fkleuver** [comment]
I think this would make a nice difference, now it looks like one parser again. What do you think?

**Comment by KFlash** [comment]
Looks better. Should I merge?

**Pull request merged**
