### PR TITLE
refactor(cherow): simplify lexer code

### PR DESCRIPTION
**Pull request by KFlash**

### CODE REVIEW

**Comment by g-plane** [comment]
Is this just adding tests?

**Comment by KFlash** [comment]
Nope. There are more to come.

**Comment by g-plane** [comment]
@KFlash Have you noticed that I have change the PR title?

**Comment by KFlash** [comment]
I noticed your `:` yes

**Comment by g-plane** [comment]
Yeah this will conform the conventional commit message and you may do it like this next time.

**Comment by KFlash** [comment]
Merging this as fixed.

**Pull request merged**
