### PR TITLE
refactor(cherow): alternative non-ascii WS optimization

### PR DESCRIPTION
**Pull request by KFlash**
I'm not suire if this is faster. Can someone benchmark this?

### CODE REVIEW

**Comment by KFlash** [comment]
@fkleuver Can you study this PR and give your opinion?

**Comment by KFlash** [comment]
No plan to merge this. Just an alternative solution. We also have to think about `maybeIdentifer`. If that can be simplified or merged into to this.

cc / @fkleuver I let you handle this

**Comment by KFlash** [comment]
This pull request **fixes 1 alert** when merging 65f8ec882ef9e372d5c3b00d40be4849dd7f1f55 into 69393aa8434e1b733825d90d9fed94345e325a0f - [view on LGTM.com](https://lgtm.com/projects/g/cherow/cherow/rev/pr-541ea4f3b437d861c8555e6e94a57dc7b884698f)

**fixed alerts:**

* 1 for Unused variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by g-plane** [comment]
Code looks good, but I don't test the perf.

**Comment by KFlash** [comment]
@g-plane What you could do was to open an issue ticket in Esprima and Acorn repo and remind them that their lexer code is very slow. Maybe they should optimize a little?

**Comment by g-plane** [comment]
I think you can do it better.

**Comment by KFlash** [comment]
@fkleuver Still no thoughts about this PR? I'm closing this now. Just re-open if needed

**Comment by KFlash** [comment]
@fkleuver Can you handle this PR?

**Pull request closed without merging**
