### PR TITLE
manage configuration in one file

### PR DESCRIPTION
**Pull request by SidKwok**
Just keep is DRY.

### CODE REVIEW

**Comment by KFlash** [comment]
@SidKwok Thanks! Are you sure this will work both for Mac/Linux and Windows? In the past I had issues with `NODE_ENV` not working cross-browser.

**Comment by SidKwok** [comment]
@KFlash It seems good to me in Mac and Linux. I don't have windows to test if it works. I will use [`cross-env`](https://github.com/kentcdodds/cross-env) to avoid the unnecessary error.

**Comment by KFlash** [comment]
@SidKwok Thanks again! Merging now!

**Comment by SidKwok** [comment]
Happy to Help `:)`

**Pull request merged**
