### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by KFlash**
**DO NOT MERGE YET**

This PR will not change how Cherow works today, but it will improve it. Mostly some internals have been redeveloped from bottom up.

**Changes:**

- will solve all issues mentioned on issue tracker for other ECMAScript parsers
- will hopefully fail everything 100% acc. TC-39
- will pass everything 100% acc. TC-39
- improves error tracking
- improvements of location tracking 
- improved performance (*about 15-25%*)
- code size reduction
- cleaner code

**New Stage 2- 3 proposals**

- Import.meta (*module code only*)
- Throw expressions

**Important**

The refactoring  will be done in 5 stages:

1. Expressions (*99.9% complete*)
2. Statements
3. Modules
4. JSX
5. Flow

### CODE REVIEW

**Comment by bd82** [comment]
again not all the tests were loaded (only new ones) i will re-trigger to see if this is consistent

**Comment by KFlash** [comment]
@bd82 Ok. BTW. There are only a few tests attached to this refactoring so far.  Around 300 or so.

**Comment by KFlash** [comment]
@bd82 Look at Travis. A lot of test files aren't run again. Something isn't right.

**Comment by KFlash** [comment]
Current refactoring will take a little longer than expected due to the fact I'm doing some crazy stuff that haven't been done before in a parser - as far as I know. This will

- increase performance
- skip 2 lookaheads
- flatten and improve unary expressions
- avoid recursion

This have been done and all tests pass, and the latest changes will be up within a few days. And the refactoring should be completed within 4 - 5 days.

**Comment by KFlash** [comment]
**update**
This PR will be completed within 4 - 5 days. *Hopefully*.

**Comment by KFlash** [comment]
Cherow has now been brought back to life. And it can parse again! The next days focus will be to fix bugs, and tests that should fail. And also add back in JSX.

**Comment by KFlash** [comment]
**Update**

Most of the issues mentioned on the issue tracker for other parsers are now solved!

**Comment by KFlash** [comment]
*update* This PR seem to be a never ending story so I will merge this to Master within a few days and fix the rest soon after in another Pr. Just now I'm switching between `ForStatement` and `JSXFragments`. After that this will be merged.

**Comment by KFlash** [comment]
This PR got to huge. Closing. Code is on Master. Validation will be done in another PR.

**Pull request closed without merging**
