### PR TITLE
change '.js' to '.mjs' for es only

### PR DESCRIPTION
**Pull request by achun**
Only one place has been modified, but some '.ts' files have changed automatically. I don't know if this is normal.

packages/cherow/rollup.config.js

```js
function output(target, format, opts = {}) {
  const ext = format === 'es' && '.mjs' || '.js';
  return {
    input: `src/${pkg.name}.ts`,
    output: { ...{ file: `dist/${mod}/${pkg.name}${minify ? '.min' : ''}${ext}`, format, name: pkg.name }, ...opts },
   //....
  }
}

### CODE REVIEW

**Comment by KFlash** [comment]
@achun There are missing source code in files. [As this one](https://github.com/achun/cherow/blob/6e19135c280a3913d3f633d9ebfb48593cbbe62a/packages/cherow-linter/dist/amd/cherow-linter.min.js)

@fkleuver Anything to say about this? Looks like a workflow issue

**Comment by achun** [comment]
The means is,,,, The single quotemark is correct?

**Comment by KFlash** [comment]
This pull request **fixes 2 alerts** when merging 6e19135c280a3913d3f633d9ebfb48593cbbe62a into 470d204f69ab2b759a3055f8ebb381c41b0b5419 - [view on LGTM.com](https://lgtm.com/projects/g/cherow/cherow/rev/pr-a0c7472c37162b059cd78a7aabc06436cc2569b3)

**fixed alerts:**

* 2 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by KFlash** [comment]
Put it on hold for now and wait and see if we get an reply.

**Comment by achun** [comment]
OK, if you need to close the PR, it's closed.
It's just a change of two lines of code. Whoever submits it will do.

When the workflow is finished, the submission will be smoother

**Comment by g-plane** [comment]
I think the bundled files should be added to `.gitignore`.

**Comment by fkleuver** [comment]
What exactly is the issue here guys?

**Comment by KFlash** [comment]
See this issue https://github.com/cherow/cherow/issues/103   and when upon creating this PR some of the minified builds have no code.

**Comment by fkleuver** [comment]
@g-plane There are a lot of quirks and edge-cases when working with lerna, occasionally resulting in weird and unexpected results. For this reason I don't have enough confidence in the build scripts yet to place these on a build server, and would rather build locally and make sure the outputs are OK before committing/publishing them.
Once the build scripts have proven themselves to be absolutely correct and reliable, we'll probably add the bundled files to `.gitignore` and more the process to a build server instead.

@KFlash  @achun Due to how unreliable rollup has turned out to be (especially in combination with typescript and lerna), unfortunately I do need to test and probably tweak every new package by hand until the build output is correct. So for now only `cherow` and `cherow-ts` can be expected to have proper build outputs. `cherow-linter`, `cherow-flow` and `cherow-minify` need to have a somewhat stable codebase before I can do sensible testing on those.

**Comment by fkleuver** [comment]
@achun The `.d.ts` files changing has something to do with line endings since they do not show up in the final commit. This can probably be fixed in `.gitattributes` - I need to look into that.
Just to be clear, *only* the `native-modules` output needs to have the `.mjs` extension, correct? Because the `es2015` and `es2017` outputs are also changed with your modification and I'm not sure if that's appropriate.

If only `native-modules` needs this adjustment then it's better to use the `mod` parameter:

`const ext = mod === 'native-modules' ? 'mjs' : 'es';`

**Comment by achun** [comment]
@fkleuver close this PR is better.

**Comment by fkleuver** [comment]
@achun Could you answer my previous question though? Then I could fix it for you/others. Is it only native-modules that needs .mjs?
I suppose another way would be to just copy the .js files to .mjs and have both, just in case ..

**Comment by KFlash** [comment]
I guess only for native modules. For now and until he reply, you can fix it? 
And also try to figure out why some of the minified builds in this PR are empty?
off topic. Latest uglify v. 4 doesn't work at all, so you have to roll back to v. 3.x

**Comment by achun** [comment]
@fkleuver 
In fact, it's not just local, it's not just the nodejs environment. The browser environment also supports it. This is a trend.

Because of the conflict between CJS and esm, the extension of '.mjs' is of practical significance.

links: 
https://github.com/standard-things/esm
Oops, I forgot another related site

糟糕, 还有一个在线支持 esm 的站点, 地址我忘记了, 就是直接支持使用 import 'path' 的站点

**Comment by g-plane** [comment]
@achun 他们的意思是您最终生成的文件中有些是空的。您看看是不是哪里配置错了？
There is some empty code in some files. Maybe something wrong with the configuration?

**Comment by achun** [comment]
@fkleuver There were some errors in the middle, from cherow-minify, because this is not the release version, I didn't check the differences carefully.

Because it's just a build, I take it for granted that at the time of the release, it will be rebuilt and will have no effect.
It seems that I made a mistake.

@g-plane 中间产生了一些错误, 来自 cherow-minify 的,  因为这不是发布版本, 我没有仔细检查差异,
因为只是 build, 我想当然的认为, 在发布版本的时候, 会重新构建, 不会有影响.
看来我犯了个错误.

**Comment by achun** [comment]
@g-plane 我怎么感觉机器翻译的要出问题啊, 不是我的本意啊

**Comment by fkleuver** [comment]
@KFlash @achun Regarding the `.mjs` - as mentioned in #103 I'll take care of this via the build process. Probably tomorrow.

@g-plane I addressed your concern regarding ignoring the build outputs in #105. As stated there I'm open for other arguments - I may not have addressed them all. Likewise, I'll take these improvements via the build process.

@achun As eluded in my [previous comment](https://github.com/cherow/cherow/pull/104#issuecomment-395963994) the only packages that currently produce valid build outputs are `cherow` and `cherow-ts`. Some typings files may be empty, that's due to `/*@internal*/` flags used to prevent exporting some internal stuff. Those modules are still exported to `.d.ts`. There should be no harm in that - placeholders for modules that "may get content in the future" are not unheard of.

I'll close this PR since the concerns are addressed in the appropriate issues now - thanks for creating them :)
If there's anything else that I missed just let me know.

**Pull request closed without merging**
