### PR TITLE
fixes #264

### LINKED ISSUE #264: 'computed' property always false in async object expression methods
**version: 1.6.8**

Test case:

```js
const key = 'bar';
const foo = { async [key] () { } };
```

Output:

```js
output = {
  type: 'Property',
  key: { type: 'Identifier', name: 'key' },
  value:
    { type: 'FunctionExpression',
      params: [],
      body: { type: 'BlockStatement', body: [] },
      async: true,
      generator: false,
      expression: false,
      id: null },
  kind: 'init',
  computed: false,
  method: true,
  shorthand: false }
```

As you can see, `computed` is false, but should be true. I've tried with generator methods, but the issue only seems to occur when the `async` keyword is present.

**Update:** Just noticed this one also produces an incorrect value for `computed`:

```js
const foo = {
  get ['bar'] () { },
};
```

Perhaps it's something to do with property keys that are preceded by a keyword?

### PR DESCRIPTION
**Pull request by KFlash**

### CODE REVIEW

**Comment by fkleuver** [comment]
`due to issues installing the workflow.`

What issues? you know you need yarn to install the old workflow right?

**Comment by KFlash** [comment]
I know and install it will overlap current workflow plus I'm still on a
temporarily internet connection so install all packages take 2h

**Comment by fkleuver** [comment]
Why don't you clone the repo twice then and leave each workflow checked out on each folder so you don't need to switch and reinstall and clean the whole shebang each time?

**Comment by KFlash** [comment]
Easier just now close this PR. Fixed in 2.0

**Comment by KFlash** [comment]
Closes this for now. Fixed in 2.0

**Pull request closed without merging**
